name: Close issues on Dev branch merged

permissions:
  issues: write
  pull-requests: write
  contents: read

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  closeIssueOnPrMergeTrigger:
    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
